### ISSUE TITLE
Show HTML special characters in form fields

### ISSUE THREAD

**Issue by awbauer** [bu-ist/bu-slideshow#18]
For text such as `Test text &nbsp; 123 &copy;`, don't render out the entities. Show as originally submitted. 

<img width="777" alt="screenshot 2015-08-26 10 36 20" src="https://cloud.githubusercontent.com/assets/1152149/9496430/5031ea64-4bde-11e5-892c-fc16f38c7a00.png">

Also tracking in SN as ENHC0013874.

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Andrew Bauer** in **#cms**. [View the logs :arrow_right:](https://buweb.slack.com/archives/cms/p1440599799000123)
