### ISSUE TITLE
Run bu_slideshow_slide_html on both public and admin

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/bu-slideshow#21]
Right now, `bu_slideshow_slide_html` only runs on the public slideshow view. It'd be great if it ran on the admin view as well, so we have control over the admin UI for custom templates too. Quick test below:

```php
function test_admin_template( $html, $slide ){
	if( "admin" == $slide->view ) {
		$output =  "<div>Doing a thing in the admin view!</div>" . $html;
		return $output;
	}
	if( "public" == $slide->view ) {
		$output =  "<div>Doing a thing in the public view!</div>" . $html;
		return $output;
	}
	return $html;
}

add_filter( 'bu_slideshow_slide_html', 'test_admin_template', 10, 2 );
```

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Andrew Bauer** in **#cms**. [View the logs :arrow_right:](https://buweb.slack.com/archives/cms/p1446482497000462)

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Andrew Bauer** in **#cms**. [View the logs :arrow_right:](https://buweb.slack.com/archives/cms/p1455305679000670)
