### ISSUE TITLE
Insert Slideshow Modal Height

### ISSUE THREAD

**Issue by awbauer** [bu-ist/bu-slideshow#23]
In WP 4.1.9, modal height is too short. 

TY @gjensen01 for [the report](https://buweb.slack.com/archives/agganis/p1453910802000002).

![image](https://cloud.githubusercontent.com/assets/1152149/12647253/4844cda6-c5a2-11e5-9cd8-0b07fe5b6a75.png)

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Andrew Bauer** in **#cms**. [View the logs :arrow_right:](https://buweb.slack.com/archives/cms/p1453999700000098)

**Comment by awbauer** [comment]
Root cause was an issue with BUModal. Patched & scheduled for deploy in CHG030720

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Andrew Bauer** in **#cms**. [View the logs :arrow_right:](https://buweb.slack.com/archives/cms/p1454429045000271)
