### ISSUE TITLE
"Shuffle Slides" option doesn't update shortcode

### ISSUE THREAD

**Issue by awbauer** [bu-ist/bu-slideshow#25]
Inserting a slideshow through the modal doesn't add the `shuffle=true` option into the shortcode.

<img width="449" alt="add_new_page_ _andrew_s_sandbox_ _wordpress" src="https://cloud.githubusercontent.com/assets/1152149/12825541/d547ccd8-cb44-11e5-8860-308e8193caf4.png">

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Andrew Bauer** in **#cms**. [View the logs :arrow_right:](https://buweb.slack.com/archives/cms/p1454611436000414)

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Andrew Bauer** in **#cms**. [View the logs :arrow_right:](https://buweb.slack.com/archives/cms/p1455305683000672)
