### ISSUE TITLE
Custom fields don't allow HTML tags

### ISSUE THREAD

**Issue by awbauer** [bu-ist/bu-slideshow#28]
Custom fields should use `wp_kses()` instead of `sanitize_text_field()` to allow HTML to be used.

ty @gjensen01 for [reporting](https://buweb.slack.com/archives/agganis/p1455217575000017).

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Andrew Bauer** in **#cms**. [View the logs :arrow_right:](https://buweb.slack.com/archives/cms/p1455305685000674)
